

spring.application.name=demo
spring.ai.openai.api-key=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
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.model=openai/gpt-oss-20b
spring.datasource.url=jdbc:postgresql://localhost:5432/csm
spring.datasource.username=postgres
spring.datasource.password=post@123
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.mail.host=smtp.gmail.com

spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.username=tharunprakash999@gmail.com
spring.mail.password=${MAIL_PASSWORD}
